---
- name: Hello World!
  hosts: all
 
tasks:

- name: Start the Apache Service
  command: ./startApache.sh chdir={{apache_home_folder}}
  ignore_errors: True

- name: Playbook Successful information below

  debug:
    msg="PLAYBOOK SUCCESSFUL ON" '{{inventory_hostname}}'
